// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("RegexGroupProvider.DesignTime")>]
[<assembly: AssemblyProductAttribute("RegexGroupProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing RegexGroupProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "RegexGroupProvider.DesignTime"
    let [<Literal>] AssemblyProduct = "RegexGroupProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing RegexGroupProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
